version: 2.1

workflows:
  version: 2.1
  publish-workflow:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master
                - /rc-.*/
          requires:
            - test

jobs:
  test:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "~/repo/package-lock.json" }}
      - run: npm install
      # Don't save cache for the security reasons?
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "~/repo/package-lock.json" }}
      - run: npm run test
      - run: npm run flow
      - run: npm run lint
      - run: npm run build

  publish:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - run: npm install
      # Don't save cache for the security reasons
      - run: npm run build
      - run:
          name: Publish package
          command: npm publish
