version: 2.1

workflows:
  test-workflow:
    jobs:
      - test:
      - build:
          requires:
            - test
  publish-workflow:
    jobs:
      - test:
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
    branches:
      only:
        - master
        - /rc-.*/

jobs:
  test:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/repo/package.json" }}-{{ checksum "~/repo/package-lock.json" }}
      - run: npm install
      # Don't save cache for the security reasons?
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "~/repo/package.json" }}-{{ checksum "~/repo/package-lock.json" }}
      - run: npm run test
      - run: npm run flow
      - run: npm run lint

  build:
    docker:
      - image: circleci/node:10.16
    steps:
      - run: npm run build

  publish:
    docker:
      - image: circleci/node:10.16
    steps:
      - run: npm run publish
