version: 2
jobs:

  test:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: npm install
      # Don't save cache for the security reasons?
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: npm run test
      - run: npm run flow
      - run: npm run lint
      - run: npm run build

  publish:
    docker:
      - image: circleci/node:10.16
    requires:
      - test
    only:
      - master
      - /rc-.*/
    steps:
      - run: npm run publish
